name: Latest blog post workflow
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 14 * * *'

jobs:
  update-readme-with-blog:
    name: Update with latest blog post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          feed_url: https://www.vagrantup.jp/feed
          count: 5
      - name: Commit and push
        uses: EndBug/add-and-commit@v4
        with:
          author_name: misyobun
          author_email: naoto0101@gmail.com
          message: 'Update readme'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
